### ISSUE TITLE
Change default ChatDurationInMinutes

### ISSUE THREAD

**Issue by PabloApser** [amazon-connect/amazon-connect-chat-interface#106]
Hi,
I´m using the chat widget fron connect embedded in a web page and I have this error:
{
    "data": {
        "statusCode": {
            "code": 429,
            "msg": "Service Quota Exceeded"
        }
    }
}
In the doc say a 429 error occurs in the following situations:

API rate limit is exceeded. API TPS throttling returns a TooManyRequests exception.
 Active chat throttling returns a LimitExceededException.

I assume in backend is ussing [StartChatContact API](https://docs.aws.amazon.com/connect/latest/APIReference/API_StartChatContact.html)

I wanna know if its possible to change the default parameter "ChatDurationInMinutes" to the minimun through this amazon-connect-chat-interface solution and minimize the impact on the service.

Thanks !

**Comment by spencerlepine** [comment]
Hi @PabloApser, any updates on this issue?

If there are any further concerns please let us know. Would like to confirm before closing the issue.

Thanks,
Spencer

**Comment by PabloApser** [comment]
Hi @spencerlepine,

I used the solution you commented. I did not do maximum load tests, but from what I saw it worked correctly.

Thank you so much !

**Comment by spencerlepine** [comment]
Awesome, glad to hear that! I will go ahead and resolve the issue for now.

Feel free to reach out or re-open if you have more questions or items to discuss.

Thanks,
Spencer
