### ISSUE TITLE
Failed at the @amzn/connect-chat-interface@1.0.0 build script

### ISSUE THREAD

**Issue by robmoores** [amazon-connect/amazon-connect-chat-interface#13]
Hi. II opened the code with Github Dektop, chcked the filees had beeen copied to my local directory, made no changes, and then ran npm install && npm build.
The build failed - the end of the messages is: 
![image](https://user-images.githubusercontent.com/53277403/111233608-3f3e8900-85e5-11eb-8ad2-bea286c4d258.png)

The logs are here:
[2021-03-15T23_11_42_474Z-debug.log](https://github.com/amazon-connect/amazon-connect-chat-interface/files/6145009/2021-03-15T23_11_42_474Z-debug.log)
[2021-03-15T23_11_42_437Z-debug.log](https://github.com/amazon-connect/amazon-connect-chat-interface/files/6145010/2021-03-15T23_11_42_437Z-debug.log)

What I'm really looking to do once Ican create a build without errors is chage the height of the chat window.
Any help on both counts much appreciated !

**Comment by johnmryan** [comment]
Hey @robmoores , do you know which version of node you are on? It should be able to build on node 10 and higher.

Also, which test case failed up there?

I just cloned a fresh version of the repo to attempt repro, and it built fine (on node 14.5).

**Comment by robmoores** [comment]
Hi @johnmryan it is node 14.5.0.

**Comment by johnmryan** [comment]
Hey @robmoores , we thought we had fixed this but for some reason Windows is not recognizing the env variable for TZ. 

While we look into a fix, you can `.skip` the TimePicker tests to unblock your build/testing. https://jestjs.io/docs/api#testskipname-fn

**Comment by robmoores** [comment]
Hi @johnmryan . Thanks for confirming and for the workaround. 
I've had a hunt around the files for where the .skip might go but to be honest I've never used Jest and have no idea where to look or where in a file to place the command. I've found  configuration/jest/setup.js and scripts/test.js but they dont seem right. Would you mind pointing me in the right direction please ?

**Comment by tscheuneman** [comment]
Hi @robmoores you should be able to go to this file, https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/src/components/Chat/ChatTranscriptor/ChatMessages/InteractiveMessages/TimePicker.test.js#L51

And change `test("Style should match the snapshot", () => {` to `test.skip("Style should match the snapshot", () => {` for example. That should skip that particular test case.

**Comment by robmoores** [comment]
@tscheuneman @johnmryan  Thanks - I skipped all of the timepicker tests, the tests competed successfully and I have a newly built amazon-connect-chat-inteface.js file. in the build\dist\static\js folder which I will now upload and test. Then onto trying to make some changes to it ! Thanks again for your help. 
Screenshot for anyone following who may experience the same  ...
![image](https://user-images.githubusercontent.com/53277403/111429139-75b4fa80-86f0-11eb-8687-b7db132f929b.png)
