### ISSUE TITLE
Struggling to change the height of the Chat Composer element

### ISSUE THREAD

**Issue by robmoores** [amazon-connect/amazon-connect-chat-interface#14]
Apologies if this post is inappropriate - I'm still learning the etiquette - so please just say so !

I cannot find where the height and border of the chat composer element can be adjusted. I've looked in
src\components\Chat\Chat.js
src\components\Chat\ChatComposer\ChatComposer.js
..and just about every other file - but can't spot it .
If you can point me in the right direction - or tell me it cant be done - that would be much appreciated.
If it can be done I will share what I learn so that others will benefit.
Thanks

**Comment by tscheuneman** [comment]
Hi Rob, you should be able to adjust the height here: https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/src/components/Chat/ChatComposer/ChatComposer.js#L98.  Either by changing min/max height, or just giving it a static height value

**Comment by robmoores** [comment]
Hi Thomas. Thank you so much - that's very kind of you to take the time to reply.
