### ISSUE TITLE
Issue to change font-size

### ISSUE THREAD

**Issue by reziakk** [amazon-connect/amazon-connect-chat-interface#159]
I'm trying to change the font-size of the elements in the chat area but it still keeps at 14px.
I've being trying to modify the file ChatTranscriptor but with no success. There is any other place to do it other then the 'Theme' folder?

I'm trying to do it in line 86 of 'defaultTheme.js' - However it doesn't replicate 

const fontsSize = {
  mini: "0.688rem", //12px
  small: "0.688rem", //13px
  regular: "0.688rem", //14px
  large: "0.688rem", //18px
  extraLarge: "0.688rem", //30px
  system: "0.688rem", // 16px
  body: "0.688rem" //14px
  
}

**Comment by mliao95** [comment]
Try adding a font-size property in one of these two places:
https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/src/components/Chat/ChatTranscriptor/ChatTranscriptor.js#L21

https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/src/components/Chat/ChatTranscriptor/ChatTranscriptor.js#L25

Let me know if that works for you.

**Comment by reziakk** [comment]
Sorry didn't get you.
Line 21 and 25 are ustyled from "styled-components" from node modules.

**Comment by reziakk** [comment]
``Didn't work
I've tried to use a very small font-size just for reference, but nothing happens.
```
const TranscriptBody = styled.div`
  margin: 0 auto;
  text-size: 6px;
`;

const TranscriptWrapper = styled(ChatTranscriptScroller)`
  background: ${props => props.theme.chatTranscriptor.background};
  -webkit-text-size-adjust: none;
  text-size: 6px;
  flex: 12 1 auto;
`;
```

**Comment by spencerlepine** [comment]
Hi @reziakk ,

Could you try similar changes using `font-size` property? [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size)

```js
const TranscriptBody = styled.div`
  margin: 0 auto;
  font-size: 6px;
`;

const TranscriptWrapper = styled(ChatTranscriptScroller)`
  background: ${props => props.theme.chatTranscriptor.background};
  -webkit-text-size-adjust: none;
  font-size: 6px;
  flex: 12 1 auto;
`;
```

**Comment by reziakk** [comment]
thanks, solved.
