### ISSUE TITLE
AccessDeniedException on read event after disconnect.

### ISSUE THREAD

**Issue by pespinozadi** [amazon-connect/amazon-connect-chat-interface#168]
Following the same issue from #128.
I use Custom Chat Interface UI, with [customChatWidget](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/customChatWidget). This problem only occurs after disconnecting without responding after starting the chat.
![image](https://github.com/amazon-connect/amazon-connect-chat-interface/assets/111007403/9fc43a56-1651-4482-8b25-c550a3d9d768)
![image](https://github.com/amazon-connect/amazon-connect-chat-interface/assets/111007403/e3ec4866-bccd-4dd3-8e62-09d82acbc30c)
I know that this type of read event cannot be sent after disconnection, because of the token, but, it happens after disconnection. It only happens 1 time after disconnecting, it is not a loop.

**Comment by spencerlepine** [comment]
Hi @pespinozadi,

I did local testing to reproduce this issue, and I can confirm that this error does not impact the expected chat behavior.

Normal chat functionality will continue to work, and this error will only appear in DevTools.

It appears that `sendReadReceipt()` is being triggered in the [`amazon-connect-chat-interface.js`](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/local-testing/amazon-connect-chat-interface.js) code at some point, AFTER the `disconnectParticipant()` was called.

Thanks,
Spencer

**Comment by pespinozadi** [comment]
> Hi @pespinozadi,
> 
> I did local testing to reproduce this issue, and I can confirm that this error does not impact the expected chat behavior.
> 
> Normal chat functionality will continue to work, and this error will only appear in DevTools.
> 
> It appears that `sendReadReceipt()` is being triggered in the [`amazon-connect-chat-interface.js`](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/local-testing/amazon-connect-chat-interface.js) code at some point, AFTER the `disconnectParticipant()` was called.
> 
> Thanks, Spencer

Why read receipt events are so much delayed?

I send this message to testing from CCP to Chat Widget Client:
![image](https://github.com/amazon-connect/amazon-connect-chat-interface/assets/111007403/b6511f3a-337f-4491-8210-6abf713f9fc1)

And read event are sent after 5 seconds (300ms):
![image](https://github.com/amazon-connect/amazon-connect-chat-interface/assets/111007403/ba07ff4c-46f4-40c1-b7d5-a431b7c80634)

These 5 seconds do not allow the sending event to be cancelled after disconnection, due to the timer. I believe, that these 300ms of the timer are of [prioritizeAndSendMessageReceipt function](https://github.com/amazon-connect/amazon-connect-chatjs/blob/master/src/core/MessageReceiptsUtil.js#L73C17-L73C42) from amazon-connect-chatjs. Am I right?.

Just because it does not affect your normal operation does not mean that the problem is not there.

**Comment by pespinozadi** [comment]
Confirm that "Amazon Connect OOTB widget" from Connect not have this problem. This detects that it is disconnected and does not send any event afterward. The problem only occurs when using the custom amazon-connect-chat-interface library from the source code.

**Comment by spencerlepine** [comment]
Hi @pespinozadi,

There is logic to throttle delay the readReceipt [[code ref]](https://github.com/amazon-connect/amazon-connect-chatjs/blob/60fcf50f5ccd623e2e10e0f65f507c489c54705a/src/core/MessageReceiptsUtil.js#L167), which delays the request. This does not break user chat experience and appears in DevTools.

Resolving the issue as basic chat functionality is working for [`customChatWidget`](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/customChatWidget) example and the error occurring is a form of race condition when `disconnect` and `sendReadReceipt` are triggered roughly at the same time.

## Error Repro:

https://github.com/amazon-connect/amazon-connect-chat-interface/assets/60903378/ae8eb9ac-4384-4232-b2fa-adf39c5d24ed

## Possible fix:

You can set the message receipts throttle time with this configuration [[documentation](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/.github/docs/MessageReceiptsFeature.md#custom-throttle-time)], in `containers/ChatWidget/index.js` component [[LINK](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/customChatWidget/src/containers/ChatWidget/index.js)]

```diff
// customChatWidget/src/containers/ChatWidget/index.js
// LINK: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/customChatWidget/src/containers/ChatWidget/index.js

import React, { useEffect } from 'react';

const ChatWidget = () => {
    const successHandler = (chatSession) => {};

    const failureHandler = (e) => {};

    useEffect(() => {
        try {
            window.connect.ChatInterface.init({
                containerId: 'chat-widget', // This is the id of the container where you want the widget to reside
                headerConfig: {      // Use the optional headerConfig and footerConfig to customize your widget
                    isHTML: true,
                    render: () => {
                    return (`<div class="header-wrapper">
                                <h2 class="welcome-text">${description}</h2>
                            </div>`)
                    }
                },
            });
+          window.connect.ChatSession.setGlobalConfig({
+              features: {
+                   messageReceipts: {
+                  shouldSendMessageReceipts: true, // DEFAULT: true, set to false to disable Read/Delivered receipts
+                  throttleTime: 5000
+                  }
+              }
+          });
        }
        catch (e) {
            error('window.connect.ChatInterface.init');
            error(e);
        }

        // ...
    }, [])

    return (
        <ChatContainer id="chat-container" device={device}>
            <ChatWrapper id="chat-wrapper" primaryColor={primaryColor} device={device}>
                <div id="chat-widget"></div>
            </ChatWrapper>
            {loading && <Spinner primaryColor={primaryColor} />}
        </ChatContainer>
    );
};

export default ChatWidget;
```

https://github.com/amazon-connect/amazon-connect-chat-interface/assets/60903378/92d5ae8a-2a93-4600-a23d-d20504be9f98
