### ISSUE TITLE
Participant Idle message is not displaying in chat

### ISSUE THREAD

**Issue by vkumar-exl** [amazon-connect/amazon-connect-chat-interface#170]
Do we have functionality to show Participant Idle message on chat window if Chat user getting Idle?

I need Implement custom text message for participants idle condition.

**Comment by spencerlepine** [comment]
Hi @vkumar-exl,

Team is not planning to add this functionality to code base, but this is possible to implement.

By modifying [ChatSession.js](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/src/components/Chat/ChatSession.js), you can utilize the [session.onParticipantIdle()](https://github.com/amazon-connect/amazon-connect-chatjs#chatsessiononparticipantidle) which is provided by [ChatJS]( https://www.npmjs.com/package/amazon-connect-chatjs) API.

The `chatSession` state is then stored in [ChatContainer.js](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/57c5f57d205335969c3259396af83861091837f8/src/components/Chat/ChatContainer.js), which can be passed down as a prop into [<Chat />](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/57c5f57d205335969c3259396af83861091837f8/src/components/Chat/Chat.js) component.

Keep in mind this code base does not use React Context, so it might not follow common pattern.

Please reach out if you have further questions. Will auto-resolve in 7 days if there are no further concerns.

Thanks,
Spencer

**Comment by vkumar-exl** [comment]
Hello @spencerlepine 

I can see below log in console but could not capture it in code. Chat end event is working and captured within the code but participant idle event is not working in same way.

INFO [2023-09-06T13:25:29.139Z] ChatJS-LPCConnectionHelperBase: this.eventBus trigger Websocket incoming message IncomingMessage {"AbsoluteTime":"2023-09-06T13:25:28.964Z","ContentType":"application/vnd.amazonaws.connect.event.participant.autodisconnection","Id":"XXXXX-18dc-4fec-8438-6d7e563f8f61","Type":"EVENT","ParticipantId":"XXXXX-8e00-4fb9-b638-f3acda4c4476","DisplayName":"vivek-XXXXX","ParticipantRole":"CUSTOMER","InitialContactId":"XXXXXX-1c09-4692-9ae4-a8c4933ab8fa"}

**Comment by spencerlepine** [comment]
Will need time to investigate and reproduce this.

In meantime, maybe the [session.onMessage()](https://github.com/amazon-connect/amazon-connect-chatjs#chatsessiononmessage) listener will work instead, this might be capturing all websocket events.

WIll double check ChatJS version that is used here too, the commit was added in this [PR](https://github.com/amazon-connect/amazon-connect-chatjs/commit/67bb09bd51792aee400710ba0c24814705db718f) not sure when it was published to npm

**Comment by vkumar-exl** [comment]
@spencerlepine 

onMessage() is triggering for other events but not for participantIdle.

We are using this https://github.com/amazon-connect/amazon-connect-chat-interface interface code.

**Comment by vkumar-exl** [comment]
@spencerlepine 

I have resolved this issue by implementing below methods and add method in event handler.

onParticipantIdle(handler) {
    return this.session.onParticipantIdle(handler);
  }
  onAutoDisconnection(handler) {
    return this.session.onAutoDisconnection(handler);
  }

_addEventListeners() {
    this.client.onParticipantIdle(data => {
      this._handleIncomingData(data);
    });
    this.client.onAutoDisconnection(data => {
      this._handleIncomingData(data);
    });
}
