### ISSUE TITLE
Broken link to resource for HostedSnippetCustomBundleFileSetup > Step 3 > customize interface.js steps

### ISSUE THREAD

**Issue by danmanning** [amazon-connect/amazon-connect-chat-interface#200]
Looking at https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/.github/docs/HostedSnippetCustomBundleFileSetup.md

In Step 3. "You can customize and upload your amazon-connect-interface.js file to your own S3 bucket or any storage server. Follow [customize interface.js steps](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/spenlep/improve-readme-documentation/DOCUMENTATION.md#features) to customize amazon-connect-interface.js."

The link for "customize interface.js steps" 404's as it references something in a specific branch (spenlep), expect this should be referencing Master but the artefact does not appear there either.

Can the link be updated.

**Comment by spenlep-amzn** [comment]
Hi @danmanning, thanks for raising issue!

This is correct link: [`https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/DOCUMENTATION.md#features`](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/DOCUMENTATION.md#features)

Raise PR to update the link: https://github.com/amazon-connect/amazon-connect-chat-interface/pull/201
