### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by narobertson42** [amazon-connect/amazon-connect-chat-interface#21]
Are there any plans to publish this project as an NPM package? The current integration into an existing react project is a little bit finicky, it would greatly improve the onboarding experience if one could add the chat interface through a package manager.

**Comment by haomingli2020** [comment]
Hi. Currently we don't have a plan for publishing it to NPM. But this is definitely something we need to do in the future. We'll discuss within the team and let you know if there's any update. Thank you for bringing this up.
