### ISSUE TITLE
Suppress console.log

### ISSUE THREAD

**Issue by jessie-wu-nyt** [amazon-connect/amazon-connect-chat-interface#24]
The logs include information like ids and there are a lot of them everywhere. It would be helpful if they were suppressed for production or there was a comment to let developers know they need to handle this.

https://github.com/amazon-connect/amazon-connect-chat-interface/search?q=console.log

**Comment by tscheuneman** [comment]
Hi Jessie,

The console.logs should get removed as apart of the production webpack build process.
