### ISSUE TITLE
Failed to execute 'measure' on 'Performance': The mark 'PERFORMANCE_CSM:markFirsttMessageDisplayed' does not exist

### ISSUE THREAD

**Issue by moshie** [amazon-connect/amazon-connect-chat-interface#241]
We are pulling in the amazon connect chat widget following the instructions here:
https://docs.aws.amazon.com/connect/latest/adminguide/add-chat-to-website.html#chat-widget-script

Once the script has finished loading and you click to open the chat window it fires off a `performance.measure` but this causes our entire app to crash.

The error below occurs in the `amazon-connect-chat-interface-client.js` file:

```
Failed to execute 'measure' on 'Performance': The mark 'PERFORMANCE_CSM:markFirsttMessageDisplayed' does not exist
```

In performing some debugging the `markFirsttMessageDisplayed` looks like it has a typo in it?

<img width="1048" alt="Screenshot 2024-04-17 at 16 36 42" src="https://github.com/amazon-connect/amazon-connect-chat-interface/assets/3974301/02774992-3060-484d-ae5a-5c62ee8a9ab2">

Also when listing the performance marks using `performance.getEntries()` there isn't an entry for `markFirsttMessageDisplayed` suggesting that it's not being defined before calling measure?

I can see that `window.customPerformanceMarker("markFirsttMessageDisplayed"),` is defined in `amazon-connect-chat-interface.js` but this never runs?

<img width="639" alt="Screenshot 2024-04-17 at 16 34 25" src="https://github.com/amazon-connect/amazon-connect-chat-interface/assets/3974301/ae5d67dc-aea1-4d66-be79-fdeb16ad928d">

I also tried Adding `amazon_connect('disableCSM', true);` but it didn't seem to fix my issue which was odd?

<img width="707" alt="Screenshot 2024-04-17 at 15 21 46" src="https://github.com/amazon-connect/amazon-connect-chat-interface/assets/3974301/8018176c-a06e-451b-8af0-c1cc09edafe1">

Any thoughts?

**Comment by moshie** [comment]
Doing some more digging I was able to replicate the issue.

1. Create a fresh [nextjs application](https://nextjs.org/docs/getting-started/installation#automatic-installation)
2. replace the `{{REPLACE WITH YOUR SNIPPET CODE HERE}}` in the code below with your own snippet code then add it to  `src/pages/index.ts`
3. boot the application in dev mode with `pnpm dev` 
4. Open in browser and also open the dev tools
5. click on the widget
6. It will not error in the console since the session is fresh
7. Reload the page and click the launcher again and the error will occur.

Snippet:
```
<script id="amazon_connect_script" dangerouslySetInnerHTML={{__html: `{{REPLACE WITH YOUR SNIPPET CODE HERE}}`}} />
  </Head>
```

Enabling this below fixes it but not sure if this is a smart thing todo since I think this will disable users chat sessions?

```
amazon_connect('disableSessionPersistence', true);
```

I managed to enable some more logs and saved out successful logs where I deleted the sessions and failure logs where I had a session already and got the error.

This Log never fires in the failure-logs file:
```
Successfully published count metrics for method WebsocketIncomingMessage
```

Messages are never received in the failure logs where as in the success logs we get:
```
ADVANCED_LOG AMZ_WEB_SOCKET_MANAGER::Message received for topic 
```

[failure-logs.log](https://github.com/amazon-connect/amazon-connect-chat-interface/files/15067937/failure-logs.log)
[success-logs.log](https://github.com/amazon-connect/amazon-connect-chat-interface/files/15067938/success-logs.log)

**Comment by mhiaror** [comment]
Hi @moshie
Can you make sure the `code snippet` is run only on client side and not server side ?
Instead of using `dangerouslySetInnetHTML`, can you try to run code_snippet only on client side using `useEffect` hook or disable SSR. example: https://nextjs.org/docs/messages/react-hydration-error

**Comment by moshie** [comment]
Hi @mhiaror 

I added the code snippet into a useEffect on the page but this time I got more errors in the console.

Ignore the red underlines that's just typescript complaining there are no types for the snippet.

This was a fresh Nextjs install as well.

<img width="580" alt="Screenshot 2024-04-23 at 08 45 15" src="https://github.com/amazon-connect/amazon-connect-chat-interface/assets/3974301/247cc18a-b0f2-46f6-ad54-2f821821d837">

<img width="783" alt="Screenshot 2024-04-23 at 08 41 07" src="https://github.com/amazon-connect/amazon-connect-chat-interface/assets/3974301/93e5cdc0-dc25-40c1-8897-c148ad2b8352">
<img width="778" alt="Screenshot 2024-04-23 at 08 41 24" src="https://github.com/amazon-connect/amazon-connect-chat-interface/assets/3974301/8dd7ed20-34bf-4a20-ae88-a1597131348d">

**Comment by mhiaror** [comment]
Thanks @moshie, for updating the code. 
Ideally, Chat application should work as expected now. 

The functional issues you previously faced should be fixed now ?

You also do not need to use below code anymore:

`amazon_connect('disableSessionPersistence', true);`

I will push a fix on my end to disable these error logs in Production.

**Comment by mhiaror** [comment]
The fix has been deployed to all regions. 

@moshie pls feel free to test and reach out if you have any additional questions.
