### ISSUE TITLE
Initialization failed 

### ISSUE THREAD

**Issue by rajivcoomar** [amazon-connect/amazon-connect-chat-interface#257]
I have followed the step of cloning the repo and performed npm run release to generate the amazon-connect-chat-interface.js

 
![image](https://github.com/user-attachments/assets/9562daa1-12fa-4a43-ae0e-14645fe57e3e)

The generated amazon-connect-chat-interface.js deployed to our s3 and made accessible file cloud front url : https://dtky8hb7pj87y.cloudfront.net/JWTDemo/public/amazon-connect-chat-interface.js

I modified the OOTB widget to add customerChatInterfaceUrl

 
![image](https://github.com/user-attachments/assets/4ec8f7bc-e2db-4718-8018-d02fa06202c1)

But I am getting the error :

 
![image](https://github.com/user-attachments/assets/2fcb114a-05cd-4a93-bf95-e3a9d8e18537)

I have not modified the git code, just cloned, build and trying to run it, but it’s failing.
Can you help me if I am missing any step ?

**Comment by alexander-sigida** [comment]
I tried this last week on Friday and today, got exactly the same result. Even did the same update as in the docs example. The funny part is that style seems to be applied:
<img width="218" alt="image" src="https://github.com/user-attachments/assets/c3d76e56-59d3-4bdd-b86d-fff4dde5b9fb">

No other errors then this one:
<img width="574" alt="image" src="https://github.com/user-attachments/assets/6ca6dc55-16ec-4a1c-8587-1ee0b648794c">

**Comment by rajivcoomar** [comment]
I found the solution, just updated the package.json 
amazon-connect-chatjs": "^2.2.4",

To

"amazon-connect-chatjs": "^2.2.5",

**Comment by xiajon** [comment]
Thanks for submitting the issue, I have merged the chatjs upgrade to fix the issue. [alexander-sigida](https://github.com/alexander-sigida) are you still facing the issue after the upgrade? The reason for this issue is a new event handler introduced for onChatRehydrated which was only available in chatjs 2.2.5 version

**Comment by alexander-sigida** [comment]
Thanks, @rajivcoomar and @xiajon, after update of the chatjs to 2.2.5 I'm no longer experiencing the issue.
