### ISSUE TITLE
Failed to init chat with 'customDisplayNames' attribute

### ISSUE THREAD

**Issue by dmakhmutov** [amazon-connect/amazon-connect-chat-interface#265]
Thank you for your work. We configured the Amazon Connect chat widget following the instructions here:
https://docs.aws.amazon.com/connect/latest/adminguide/add-chat-to-website.html#chat-widget-script

We used additional configurations like:
```js
amazon_connect('customDisplayNames', {
  header: {
    headerMessage: 'Hi there! We are online!',
  },
  transcript: {
    systemMessageDisplayName: 'Agent',
    botMessageDisplayName: 'Kate'
  }
});
```
and everything works fine till this morning. This morning we faced issues (screenshots below)

![image](https://github.com/user-attachments/assets/8b51aee0-5176-4848-868f-d130acc93b70)
![image](https://github.com/user-attachments/assets/6626617a-b651-4022-9880-457cf93b0077)
![image](https://github.com/user-attachments/assets/ca5c8bc6-47e3-4ae2-acf0-3ef03c1a14e4)

after commenting `amazon_connect('customDisplayNames', {..}` the chat restored to work

UPD: In the documentation, https://docs.aws.amazon.com/connect/latest/adminguide/pass-custom-styles.html#pass-override-system says that all fields are optional.
I've added endChatButtonText and Chat restored
```
amazon_connect('customDisplayNames', {
 ....
  footer: {
     endChatButtonText: 'End Chat',
   }
}
```

**Comment by agarwhi** [comment]
We hope fix resolved your concern. If the problem recurs, please reopen this ticket, and we'll be glad to assist you further.

**Comment by dmakhmutov** [comment]
@mliao95  Yes, It helped. Thank you!
