### ISSUE TITLE
Receiving attachment files

### ISSUE THREAD

**Issue by ebony-g** [amazon-connect/amazon-connect-chat-interface#30]
Hi,

May I know if there's an event to call when the chat receives an attachment file? Seems like cannot find it.

Regards,
Ebony

**Comment by swiszm-amazon** [comment]
Received attachments are included in `onMessage` handler along with regular text messages.

If you are trying to add custom behavior when receiving an attachment, you can look at this example for adding audio notifications https://github.com/amazon-connect/amazon-connect-chat-interface#audio-notifications

For attachments, it would look something like:

```
this.session.onMessage(event => {
  const { chatDetails, data } = event;
  if (data.Type === "ATTACHMENT") {
    // do something
  }
});
```
