### ISSUE TITLE
Q: Is there anyway to run the chat UI itself locally?

### ISSUE THREAD

**Issue by evanlarkin10** [amazon-connect/amazon-connect-chat-interface#38]
Is it possible to run this project locally during development in order to see modifications before building it and importing it for another webpage?

**Comment by sanjusunny** [comment]
You can enable the webpack-dev-server option to enable live-reload to see your changes in realtime in the browser when developing, speeds up the process. I can share more details if needed but basically as below. You can also use TamperMonkey in Chrome to inject your local dev files into your production site to test it out without deploying (particularly helpful to see if there are styling conflicts with the destination site)

"serve": "NODE_ENV=development npx webpack serve --config configuration/webpack.config.dev.js",

new HtmlWebpackPlugin({
      template: 'src/index.html'
    }),
