### ISSUE TITLE
API Call for JWT Token is called twice

### ISSUE THREAD

**Issue by IsaacTrevino** [amazon-connect/amazon-connect-chat-interface#39]
Upon using the Chat Snippet generated by Amazon Connect, and using the provided method by adding:
`amazon_connect('authenticate', ....`

The chat widget seems to work. However, two calls are being made, which results in two chats being created for the agent who receives the chat.

I am using React.js and placing the widget in the `index.html` code.

Could this be my web app rendering twice? And if I am using the widget without a security requirement, the widget works fine only generating a single chat for the agent.

**Comment by swiszm-amazon** [comment]
Can you please provide AWS region, timestamp, widgetId (and contactId if you have that as well) to help us investigate?

**Comment by jiahaoyu6666** [comment]
We didn't get back from this question, closed this issue.
