### ISSUE TITLE
Chat is not disconnected when closing the window

### ISSUE THREAD

**Issue by Zyckzto** [amazon-connect/amazon-connect-chat-interface#40]
I'm trying to end the chat and disconnect the participants when the user closes the browser window by doing something like:

```
window.addEventListener('beforeunload', () => {
  chatSession.endChat();
});
```
But it is not working since endChat is a promise, since it is asynchronous code, the window will close before the promise has been completed.

Is there a way to use the [sendBeacon](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) method or enable the `keepalive` flag if the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/fetch) is being used as the HTTP client?
Is there any other way to disconnect participants from the chat once the user closes the window?

**Comment by yuanyuyu-amazon** [comment]
An option may be to configure your contact flow to periodically ask the customer to respond while in queue. You can accomplish this by using the branches available on a wait block, Timeout and Customer return. See https://docs.aws.amazon.com/connect/latest/adminguide/wait.html

You can also have your agents end chats when customers are un-responsive and configure a disconnect flow to re-queue customers if they respond back in time. See https://docs.aws.amazon.com/connect/latest/adminguide/set-disconnect-flow.html
