### ISSUE TITLE
Markdown on Interactive Messaging

### ISSUE THREAD

**Issue by LahiruWijesuriya** [amazon-connect/amazon-connect-chat-interface#47]
Hi team,

When rendering a ListPicker InteractiveMessage or ChatMessage, how can we insert a [link](www.link.com) as such?

I've tried various methods, i.e. 
https://codesandbox.io/s/snowy-field-r8d3c?file=/src/App.js:481-560 
https://github.com/remarkjs/react-markdown/issues/12
https://docs.aws.amazon.com/connect/latest/adminguide/enable-text-formatting-chat.html

**Comment by haomingli2020** [comment]
Currently we don't support text formatting in interactive messages. For chat messages you need to call StartChatContact API with the `SupportedMessagingContentTypes` set to `[ "text/plain", "text/markdown" ]`, then send a message with content type `text/markdown`. It should be successfully sent through and you can have your own implementation to render it correctly. 
To insert a link, just follow the common markdown syntax for links - https://www.markdownguide.org/basic-syntax/#links.

Does this answer your question?

**Comment by mhiaror** [comment]
Closing, no response from the issue creator.
