### ISSUE TITLE
[Q] Is there any way to load the previous contact transcript with same user id 

### ISSUE THREAD

**Issue by MichaelM193** [amazon-connect/amazon-connect-chat-interface#55]
Does anyone has the same requirement to load the unique userid's transcript from contactId? if anyone has those kind of experience, cloud we have a discussion of it?

**Comment by haomingli2020** [comment]
Hi,
By 'to load the unique userid's transcript from contactId', do you mean to fetch transcript for a specific participant given the contactId? A specific chat participant could be the end-user,  the agent or other roles participating in the chat contact.
See the response for GetTranscript API - https://docs.aws.amazon.com/connect-participant/latest/APIReference/API_GetTranscript.html

**Comment by haomingli2020** [comment]
Chatted offline. Provided guidance on fetching s3 transcripts for all the contact Ids. Let me know if there's further question

**Comment by jiahaoyu6666** [comment]
We didn't get back from this question, closed this issue.
