### ISSUE TITLE
Browser Notifications

### ISSUE THREAD

**Issue by LahiruWijesuriya** [amazon-connect/amazon-connect-chat-interface#57]
Do browser notifications need to be manually implemented in this repo? If so, how?

**Comment by jiahaoyu6666** [comment]
Hi @LahiruWijesuriya, currently browser notification is not supported in this repo. However, you can add a chat widget to your website that is hosted by Amazon Connect. Please take a look this documentation: https://docs.aws.amazon.com/connect/latest/adminguide/add-chat-to-website.html
