### ISSUE TITLE
UI localization

### ISSUE THREAD

**Issue by pymia** [amazon-connect/amazon-connect-chat-interface#61]
The current UI is only in English. Ask for a feature that the user can change the language of a custom chat widget based on the language the user selects.

**Comment by haomingli2020** [comment]
Yes this is one of our backlog tasks and will be worked on soon. We don't have an ETA yet though. 
Are you currently blocked on this? Is there a specific date you are looking at?

**Comment by haomingli2020** [comment]
Localization has been added to this repo - https://github.com/amazon-connect/amazon-connect-chat-interface/commit/7bd67c5ec3a9a3dda6482d8db5cd508045204df8. Please take a look and let us know if you have further questions.
