### ISSUE TITLE
Unable to change name of "SYSTEM_MESSAGE" and "BOT" in chat interface

### ISSUE THREAD

**Issue by rickaws** [amazon-connect/amazon-connect-chat-interface#62]
I have looked through the different functions but it is unclear how the names for the initial flow "SYSTEM_MESSAGE" and Lex interaction "BOT" are set. Any ideas how this can be accomplished or example be modified to provide flexibility to this?

**Comment by haomingli2020** [comment]
Hi, those are the value of `displayName` field in the message item fanned out through web socket or returned by GetTranscript call. It's determined by the backend.
The render logic is here - https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/src/components/Chat/ChatTranscriptor/ChatMessages/ChatMessage.js#L155. You can add your own code here to process it when rendering.
Let me know if you have more questions

**Comment by jiahaoyu6666** [comment]
We didn't get back from this question, closed this issue.

**Comment by rickaws** [comment]
Thanks, apologies for the late response. This worked, was able to adjust the name to a customer-defined name.
